### ISSUE TITLE
this mod heavily slows loading with JEI

### ISSUE THREAD

**Issue by lag42** [CAS-ual-TY/GunCus#1]

**Comment by CAS-ual-TY** [comment]
Well, More than 100k items per gun. I dont know how I could fix that. Its the same when opening creative tabs. I will add an option to turn off the making of gun creative tabs with all combinations possible in the config file. This should then also not add them to JEI.

Thanks for pointing that out. I will close this when the option as been added.

**Comment by CAS-ual-TY** [comment]
Fixed in 0.5
